Demo.WebMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.WebMvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Demo.WebMvc/Controllers/Html5Controller.cs
using Demo.Web.Html5;
using System;
using System.Threading;
using System.Web.Mvc;

namespace Demo.WebMvc.Controllers
{
    public class Html5Controller : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        #region WebSocket
        public ActionResult WsView()
        {
            return View();
        }

        public void WsTask()
        {
            HttpContext.AcceptWebSocketRequest(ctx =>
            {
                int.TryParse(ctx.QueryString["count"], out int count);
                return WebSocketManager.RunTask(ctx, wsm =>
                {
                    for (int i = 0; i < count; i++)
                    {
                        var message = string.Format("{0:yyyyMMdd HH:mm:ss} 消息{1}", DateTime.Now, i + 1);
                        wsm.SendMessageAsync(message);
                        Thread.Sleep(1000);
                    }
                });
            });
        }
        #endregion
    }
}

Demo.WebMvc/Controllers/PdfController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.WebMvc.Controllers
{
    public class PdfController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Demo.WebMvc/Views/Home/Index.cshtml
<h2>首页</h2>

<blockquote>
    <p>欢迎访问我的.NET示例程序集。</p>
    <footer>版权所有 <cite title="Source Title">KNOWN</cite></footer>
</blockquote>

Demo.WebMvc/Views/Html5/Index.cshtml
<h2>HTML5首页</h2>

Demo.WebMvc/Views/Html5/WsView.cshtml
<h2>WebSocket</h2>

<div class="form-inline">
    <div class="form-group">
        <label for="count">消息数</label>
        <input type="text" class="form-control" id="count" placeholder="服务端返回的消息数">
    </div>
    <button class="btn btn-primary" onclick="wsTest()">提交</button>
</div>

<blockquote>
    <ol id="msg"></ol>
</blockquote>

@section Foot{
    <script>
        var WsUtil = {
            msg: document.getElementById('msg'),
            ws: null,
            connect: function (url, callback) {
                var _this = this;
                _this.msg.innerHTML = '';
                _this.appendMsg('正在连接......', '#00f');
                _this.ws = new WebSocket(url);
                _this.ws.onopen = function () {
                    _this.appendMsg('客户端已连接', '#00f');
                    if (callback) {
                        callback(_this.ws);
                    }
                }
                _this.ws.onmessage = function (evt) {
                    _this.appendMsg(evt.data);
                }
                _this.ws.onclose = function () {
                    _this.appendMsg('客户端已断开连接', '#00f');
                }
                _this.ws.onerror = function (evt) {
                    _this.appendMsg(evt.data, '#f00');
                }
            },
            close: function () {
                if (this.ws) {
                    this.ws.close();
                    this.ws = null;
                }
            },
            appendMsg: function (message, color) {
                var li = document.createElement('li');
                li.style.color = color || '#000';
                li.innerHTML = message;
                msg.appendChild(li);
            }
        }

        function wsTest() {
            var count = document.getElementById('count').value;
            var url = 'ws://@Request.Url.DnsSafeHost:@Request.Url.Port/html5/wstask?count=' + count;
            WsUtil.connect(url, function (ws) {
                ws.send('test');
            });
        }
    </script>
}

Demo.WebMvc/Views/Pdf/Index.cshtml
<h2>Pdf预览</h2>

<div>
    <button class="btn btn-primary" onclick="previewPdf('@Url.Content("~/assets/files/Nginx安全配置指南技术手册.pdf")')">预览</button>
</div>
<div id="fileViewer" style="height:500px;"></div>

@section Foot{
    <script src="~/assets/js/pdfobject.min.js"></script>
    <script type="text/javascript">
        function previewPdf(url) {
            var reg = new RegExp('.pdf$');
            if (reg.test(url)) {
                PDFObject.embed(url, '#fileViewer');
            } else {
                $('#fileViewer').html('<img src="' + url + '" />');
            }
        }
    </script>
}

Demo.WebMvc/Views/Shared/Menu.cshtml
<ul class="nav nav-sidebar">
    <li class="active"><a href="@Url.Action("Index", "Html5")">Html5 <span class="sr-only">(current)</span></a></li>
    <li>@Html.ActionLink("WebSocket", "WsView", "Html5")</li>
    <li class="active"><a href="@Url.Action("Index", "Pdf")">Pdf <span class="sr-only">(current)</span></a></li>
</ul>

Demo.WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Microsoft.NET示例程序集。ASP.NET MVC、HTML5等等。">
    <meta name="author" content="known">
    <title>我的.NET示例集</title>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/css/demo.css" rel="stylesheet" />
    @RenderSection("Head", false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">.NET示例集</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="#">Settings</a></li>
                    <li><a href="#">Profile</a></li>
                    <li><a href="#">Help</a></li>
                </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Search...">
                </form>*@
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                @Html.Partial("Menu")
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/assets/js/demo.js"></script>
    @RenderSection("Foot", false)
</body>
</html>